services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # Qdrant gRPC API
      - "6334:6334"  # Qdrant HTTP API
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=host.docker.internal
    depends_on:
      - qdrant
    restart: on-failure

  frontend:
    build:
      context: ./frontend_user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_user:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: on-failure

volumes:
  qdrant_data:
  frontend_node_modules:

networks:
  default: